# Generated by Django 5.1.1 on 2024-10-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_alter_agent_id_alter_category_id_alter_followup_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='age',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='lead',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='destination_city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='destination_country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='destination_state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='destination_zip',
            field=models.CharField(default='00000', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='estimated_ship_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes_from_shipper',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='origin_city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='origin_country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='origin_state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='origin_zip',
            field=models.CharField(default='00000', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_other',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='ship_via',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='total_tariff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='vehicle_deposit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='vehicle_make',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='vehicle_model',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='vehicle_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='vehicle_tariff',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='vehicle_type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='vehicle_year',
            field=models.CharField(default='Unknown', max_length=4),
        ),
        migrations.AlterField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
