# Generated by Django 5.1.1 on 2024-10-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_alter_lead_vehicle_deposit_alter_lead_vehicle_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='total_tariff',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
