# Generated by Django 5.1.1 on 2024-10-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_alter_lead_deposit_alter_lead_total_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='deposit',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='total_tariff',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='vehicle_deposit',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='vehicle_tariff',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
