# Generated by Django 5.1.1 on 2024-10-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_rename_fax_lead_faxx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='destination_zip',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='origin_zip',
        ),
        migrations.AddField(
            model_name='lead',
            name='destination_zip_code',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='origin_zip_code',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
